### ISSUE TITLE
Register account on `github.com` and few other resources

### ISSUE THREAD

**Issue by wilensky** [wilensky/ba-od-idp#1]
This is the very first issue we are facing with. It will make our further collaboration possible.

* **github** - Here we will be working together on code and the rest.
* **HTMLAcademy** - This site will allow us to track progress of our studying process.

So ...

1. [x] Register account on **[:link: github.com][gh]**.
1. [x] Register account on **[HTMLAcademy][ha]**.

Issue will be closed when all group members will be registered on sites listed above.

[gh]:http://github.com
[ha]:https://htmlacademy.ru/

**Comment by wilensky** [comment]
Homework for lesson 1.

**Comment by gorbanev92** [comment]
=)

**Comment by ksahipuk** [comment]
Hello, world!

**Comment by tanguera** [comment]
I'm  Nataly

**Comment by derganyj** [comment]
Hi!

**Comment by AndrewVoronin** [comment]
Hello!

**Comment by sergeyshpota** [comment]
done

**Comment by JulySi35** [comment]
Super

**Comment by wilensky** [comment]
Added collaborators:

1. @gorbanev92 
1. @ksahipuk 
1. @tanguera 
1. @derganyj 
1. @AndrewVoronin 
1. @sergeyshpota 
1. @JulySi35

**Comment by Koval2907** [comment]
Good day!

**Comment by wilensky** [comment]
So, we are almost here. Only **1 person** left to appear.
As the majority rules, here is the link for materials of **[Lesson №1][l1]**.

> This issue will be closed as soon as we reach :nail_care: 10 collaborators.

[l1]:https://github.com/wilensky/ba-od-idp/wiki/L1:-Web-introduction

**Comment by wilensky** [comment]
@AndrewBor1 [Lesson №1](https://github.com/wilensky/ba-od-idp/wiki/L1:-Web-introduction)

**Comment by wilensky** [comment]
@VityaBeetroot **[Lesson №1](https://github.com/wilensky/ba-od-idp/wiki/L1:-Web-introduction)**

**Comment by wilensky** [comment]
All welcome!
Issue #1 is **resolved**.

> Lesson №2 starts tomorrow 28.11.2015@9:00

**Comment by VityaBeetroot** [comment]
Дякую. До зустрічі.
