### ISSUE TITLE
Уточнение по домашнему заданию 

### ISSUE THREAD

**Issue by JulySi35** [wilensky/ba-od-idp#13]
Меня не было на занятии 28 декабря. Мне прислали страницу, которую вы верстали на занятии. Не понятно как добавлять страницы на сайт. И по ссылкам еще вопрос: какую информацию из них взять ?

**Comment by JulySi35** [comment]
Что должны содержать страницы ABOUT and CONTACT.

**Comment by AndrewVoronin** [comment]
href="#"
