### ISSUE TITLE
Create your first git commit to the repository

### ISSUE THREAD

**Issue by wilensky** [wilensky/ba-od-idp#2]
> :grey_exclamation: Read attentively.
> :grey_exclamation: **`$`** in the beginning of command sign **shouldn't be copied**. It is used just for denoting shell command.
> :grey_exclamation: **`{your_username}`** should be **replaced with your github username without curly braces**.

So, first of all we should **clone our repository**:
Go to the directory where you would create your project directory. For example, if you want to create your project under `C:\www\ba-od-idp` you should run `Git Bash here` in `C:\www`.
Then clone repository.
```bash
$ git clone https://github.com/wilensky/ba-od-idp.git # this will clone repository right to your machine
$ cd ba-od-idp # moving into directory
```

---

After cloning the repository we are on `master` branch, but we remember that we should should **create and switch to our own branch**. For this purpose we do:
```bash
$ git checkout -b feature/hello-world_{your_username} # this will create and switch you to the new branch
$ git status # check
```
> :exclamation: Mention **`{your_username}`**. This means that **you should write your own github username instead of it (_without {}_)**.

---

Than you should **create your own folder** which **name will be your github username**.
```bash
$ mkdir {your_username} # this will create a folder with name you provide
```
> :exclamation: Don't forget **`{your_username}`**.

---

After creating your folder, we should create **at least one file** to be able **to commit this folder**.
```bash
$ touch {your_username}/.gitkeep # it will create empty file in your folder
$ git status # check
```
> :exclamation: **`{your_username}`**
> :grey_exclamation: Empty folders can't be commited.

---

Then, adding files to the **Index**:
```bash
$ git add * # this will add your new creations to the Index
$ git status # check what changed after we added files to index
```

---

Finally we can do our first **commit**:
```bash
$ git commit -m "Your first commit message!" # this will commit all that was previously added to index
$ git status # check what changed after commit
```
And remember how we check our commit history
```bash
$ git log # this will show you your commits (first commit)
```
---

This is it! The most interesting part we will do in the beginning of the lesson.

**Comment by wilensky** [comment]
@gorbanev92, @ksahipuk, @tanguera, @derganyj, @AndrewVoronin, @sergeyshpota, @JulySi35, @Koval2907, @AndrewBor1, @VityaBeetroot

Все кому удалось пройти этот нелёгкий путь и увидеть в конце свой коммит с помощью комманды `git log` - оставьте свой короткий **комментарий под этим заданием**.
А как и у кого получилось мы узнаем в начале следующей лекции.

---

> [Полезные материалы][git_wiki]
> Next lesson: 30.11.2015@18:00

[git_wiki]:https://github.com/wilensky/ba-od-idp/wiki/L2:-Git

**Comment by ksahipuk** [comment]
done. Вроде бы.

**Comment by AndrewBor1** [comment]
Получилось! Вижу свой коммит!:)

**Comment by wilensky** [comment]
@ksahipuk, всё закоммитилось в локальный репозиторий :)
@AndrewBor1, найс :)

**Comment by AndrewVoronin** [comment]
I see my commets:

commit 2ca3098c062bb7b65b1ee341bc0b2ec17e32eb8d
Author: AndrewVoronin <a.voronin.n@gmail.com>
Date:   Sun Nov 29 22:07:23 2015 +0200

**Comment by tanguera** [comment]
fatal дважды - что за беспредел? где должна быть локальная папка, названная моим именем пользователя? в папке репозитории? у меня она в папке www?! я запартачила, как откатить назад или повторить все заново, или ?

**Comment by tanguera** [comment]
@wilensky капец... fatal дважды - что за ...? выдал текст написать свой адрес, написать кто я через команды git config --global name.email "...." ? где должна быть эта локальная папка, названная моим именем пользователя? в папке репозитории? у меня она в папке www?!

**Comment by VityaBeetroot** [comment]
Ребята, кто сделал, опишите порядок действий.

**Comment by ksahipuk** [comment]
Вам нужно создать пустую папку у себя на компьютере. Зайти в эту папку, запустить Git из нее (так все файлы сохранятся в созданную папку).
Затем в командной строке (открытый Git) выполнить последовательно команды, описанные в задании. Просто подряд. Их можно копировать (только без $)
Что будет происходить по мере выполнения команд:
1. Склонируется репозиторий ba-od-idp - т.е. загрузится папка с файлами отсюда - github.com/wilensky/ba-od-idp - это будет ваш локальный репозиторий. 
2. В локальном репозитории будет создана и переключена новая именная (с вашим ником на GitHub) ветка.
3. Затем создается именная (с вашим ником на GitHub) директория (папка) в вашем локальном репозитории (на вашем компьютере) по адресу - ваша папка\ba-od-idp\именная папка
4. В именной папке создается пустой файл.
5. Добавляем файлы в индекс 
6. Коммитим новую папку с файлом в наш локальный репозиторий
7. Проверяем коммит командой Лог.

Объяснила, как смогла. :)

**Comment by wilensky** [comment]
@ksahipuk 
---
![Supression ribbon](http://oyster.ignimgs.com/mediawiki/apis.ign.com/battlefield-3/f/f4/Suppression_rib.png)

**Comment by ksahipuk** [comment]
@wilensky а медальку дадут?

![evil](https://scontent-frt3-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/425044_505188102840396_644469658_n.jpg?oh=b225b5b77eec059fcdfb3068c47a8aa9&oe=56F57AF1)

**Comment by wilensky** [comment]
@ksahipuk _/ Пионер `markdown` /_

---

![MVP ribbon](http://oyster.ignimgs.com/mediawiki/apis.ign.com/battlefield-3/a/a9/MVP_rib.png "MVP ribbon")

---

> 1 медаль = 10 нашивок

**Comment by derganyj** [comment]
@wilensky NEED HELP!
I have a fatal error. I can't understand what does it mean: "fatal: Not a git repository (or any of the parent directories): .git"

**Comment by derganyj** [comment]
I've done:
"commit 21cbc862d22ec698c74dd1f0eb2f2b32a834ef36
Author: Ilia Cherniaiev <Ilia Cherniaiev>
Date:   Mon Nov 30 12:04:04 2015 +0200

    This is SO GREATE"

**Comment by wilensky** [comment]
@derganyj, разобрался - молодец.

---

> fatal: Not a git repository (or any of the parent directories)

Значит, что там где пытаются производить операции над репозиторием - **его нет**.

1. Не была выполнена ни комманда `git init`, ни `git clone`, а это значит **репозитория нет**
1. Вы всего лишь находитесь не в той папке где находится репозиторий (_такое тоже бывает_)

**Comment by wilensky** [comment]
@tanguera, вспомни _[StackOverflow][so]_, [нет конструктивного вопроса][c1] - не будет ответа.
Сложно понять, что не получается пока нет хотя бы текста ошибки или последовательности действий которые приводят к ней.
Одним из примеров правильно заданного вопроса я вляется [этот комментарий][c2].

За **первый правильно заданный вопрос** по проблеме @derganyj получает нашивку.

---

![MVP ribbon](http://oyster.ignimgs.com/mediawiki/apis.ign.com/battlefield-3/a/a9/MVP_rib.png "MVP ribbon")

[so]:http://stackoverflow.com
[c1]:https://github.com/wilensky/ba-od-idp/issues/2#issuecomment-160479206
[c2]:https://github.com/wilensky/ba-od-idp/issues/2#issuecomment-160580307

**Comment by JulySi35** [comment]
Job is done!

commit 46eb93aed0029308f349bca941f443ab053fb4c3
Author: July <aventura2011@mail.ru>
Date:   Mon Nov 30 12:39:10 2015 +0200

    Hello world!

**Comment by derganyj** [comment]
@wilensky Yes, I was in wrong directory.
p.s. Stripes and Tickets?) I feel the "Battlefield" in you...

**Comment by gorbanev92** [comment]
Admin@AdminPC MINGW32 /c/www (feature/hello-world_gorbanev92)
$ git log #
commit cb2bfa1f0cdeb11e52448394cf7c0a94e841e071
Author: gorbanev92 <gorbanev92@ukr.net>
Date:   Tue Dec 1 13:12:15 2015 +0200

    =)

**Comment by gorbanev92** [comment]
Я так понимаю, что я справился!?)

**Comment by JulySi35** [comment]
git config user.name 
git config user.email
Я так понимаю, не у всех надо было такие команды писать?

**Comment by gorbanev92** [comment]
я писал эти команды!)

**Comment by AndrewBor1** [comment]
config скорее всего писать надо было всем, а вот на master ветку кто-то попал автоматом, а кому-то пришлось прописывать вручную.

**Comment by JulySi35** [comment]
а от чего это зависит ?

**Comment by sergeyshpota** [comment]
$ git log
commit a4fcfa03cfbd544eb3fec29c0e0e17008348688e
Author: Sergey Shpota <od311289ssv@gmail.com>
Date:   Mon Nov 30 15:03:40 2015 +0200

    It's my first commit!

**Comment by tanguera** [comment]
На команде git checkout выдает ошибку "not a git repository( or any of the parent directories)"
Я поняла, что надо активировать папку, только какую, если пишу git init  - создается папка .git в папке www. Это верно? или надо в клонированной папке?

**Comment by JulySi35** [comment]
в клонированной

**Comment by tanguera** [comment]
папка одноименная, где должна быть? в www или в ba-od-idp?

**Comment by tanguera** [comment]
$ git log
commit 57cd0f2cd8c45d9bc07bbc5e02405733cd5c23a6
Author: tanguera <nk36bk.ru@gmail.com>
Date:   Mon Nov 30 15:49:20 2015 +0200

    Наконец-то!

**Comment by wilensky** [comment]
@tanguera, папка `.git` которая и символизирует репозиторий должна находится в корне каждого проекта. То есть, если наш проект находится по пути `/c/www/ba-od-idp`, то соответственно и папка `.git` должна находится в `/c/www/ba-od-idp`.
Только эту папку мы **никогда руками** не копируем/вставляем/перемещаем/создаём, она должна появится в результате _инициализации_ или _клонирования_ репозитория. А клонировать/инициализировать сам репозиторий мы должны в той папке где будет жить наш проект.

> Ну и на последок надеюсь, что репозиторий для этого домашнего задания все **склонировали**, а не ~~инициализировали~~.

**Comment by tanguera** [comment]
в начале git clone само собой, ну а дальше? получается не надо было делать git init? а как же тогда, если fatal?

**Comment by wilensky** [comment]
@tanguera, `git clone` исключает `git init` и наоборот.

**Comment by tanguera** [comment]
@wilensky почему тогда выдавалась ошибка?

**Comment by wilensky** [comment]
@tanguera, снова ничего невозможно сказать и посоветовать потому что нет последовательности выполнения комманд.

Лучше всего screenshot окна в котором ведутся работы с видимыми предыдущими коммандами. Потому что нужно видеть ответы комманд и так можно более чотко проанализировать работу, т.к. могут присутствовать моменты на которые, по началу, можно необратить внимания.

**Comment by tanguera** [comment]
я нашла своё упущение, я не вошла в папку, которую склонировала
сейчас в четвертый раз удалила и по новой выполнила, вот что выдалось) 
$ git log
commit c220bcf0f561630333490a94eba91f13b8a933c5
Author: tanguera <nk36bk.ru@gmail.com>
Date:   Mon Nov 30 16:48:44 2015 +0200

    Finally!

commit 470eaa86b24358830ab50b9a855aedfdc29dadd7
Author: G. Wilensky <wilensky@users.noreply.github.com>
Date:   Fri Nov 27 20:08:41 2015 +0200

    + Repository page link

commit ada89e369bcc1ce3f8fa13152e395fe205a0cd76
Author: G. Wilensky <wilensky@users.noreply.github.com>
Date:   Wed Nov 25 13:09:16 2015 +0200

    Added P.S. message

commit 8fc9ffa3d7e221f7709dd2632889830d57d910f9
Author: G. Wilensky <wilensky@users.noreply.github.com>
Date:   Wed Nov 25 13:05:57 2015 +0200

    Updated `readme.md`

**Comment by VityaBeetroot** [comment]
+. Дякую Павлу та Андрію. Все стало зрозімуло

**Comment by wilensky** [comment]
# Done
