### ISSUE TITLE
Create your first `Hello world` HTML page

### ISSUE THREAD

**Issue by wilensky** [wilensky/ba-od-idp#4]
Create HTML file named **`hello_world.html`** with following text.

## Requirements:
- Page title - **Gangnam style by {your_username}**
- **Formatting should be same** as below
- Created HTML page should be **valid** HTML5 page
- Created HTML page should be **`commit`**ed and **`push`**ed
- Commit must be on your own branch
- You should post your comment here with **commit hash**

> :exclamation: Remember to check that you are on your own branch that we created on previous lesson. Please.

## Allowed tags:
`h1 .. h6`, `p`, `br`

### Gangnam style

Najeneun ttasaroun inganjeogin yeoja
Keopi hanjanui yeoyureul aneun pumgyeok inneun yeoja
Bami omyeon simjangi tteugeowojineun yeoja
Geureon banjeon inneun yeoja

Naneun sanai
Najeneun neomankeum ttasaroun geureon sanai
Keopi sikgido jeone wonsyat ttaerineun sanai
Bami omyeon simjangi teojyeobeorineun sanai
Geureon sanai

Areumdawo sarangseureowo
Geurae neo hey geurae baro neo hey

Areumdawo sarangseureowo
Geurae neo hey geurae baro neo hey

Jigeumbuteo gal dekkaji gabolkka

Oppa Gangnam Style
Gangnam Style

**Comment by wilensky** [comment]
@gorbanev92, @ksahipuk, @tanguera, @derganyj, @AndrewVoronin, @sergeyshpota, @JulySi35, @Koval2907, @AndrewBor1, @VityaBeetroot

![](http://risovach.ru/upload/2014/03/mem/polnostyu-lomaj_45552804_orig_.jpg)

**Comment by AndrewVoronin** [comment]
I could do.
commit a66d93dd9e32979b1dabdd02f71fe75d53ec6e3b
Author: AndrewVoronin <a.voronin.n@gmail.com>
Date:   Tue Dec 1 22:59:49 2015 +0200

    I create HTML file hello_world.html

**Comment by wilensky** [comment]
Ах, ну да.

Вот с помощью [этого][online_editor] вы сможете проверить всё что накодили.

Сверху пишем HTML, снизу видим результат. `<title>` там не отобразится, но просмотреть `<body>` сможете свободно.

> @gorbanev92, @ksahipuk, @tanguera, @derganyj, @AndrewVoronin, @sergeyshpota, @JulySi35, @Koval2907, @AndrewBor1, @VityaBeetroot

[online_editor]:http://www.onlinehtmleditor.net/

**Comment by ksahipuk** [comment]
Done.
```
commit a49c3597f74f074c2fe9dc8eed91d994bfac46e5
```

**Comment by wilensky** [comment]
@ksahipuk и всем остальным.
Хеш коммита мы вставляем **просто как текст**, не оборачивая в блок кода и тд. Таким образом хеш из комментария выше, простым движением руки превращается в

> a49c3597f74f074c2fe9dc8eed91d994bfac46e5

превращается в ссылку на сам коммит, и даже если был использован полный хеш (_как выше_), то он будет сокращен до первых 7ми знаков и также превращен в кликабельную ссылку.

**Comment by gorbanev92** [comment]
7b37ea6
ceff9d5

**Comment by derganyj** [comment]
There are not <img/> tag in the list, so images are not allowed in the project?

**Comment by Koval2907** [comment]
8aef91e

**Comment by wilensky** [comment]
@derganyj, @gorbanev92 и всем остальным.
Можно всё, что указано в тикете. Невыполнение условий является незакрытый issue, что влечёт за собой незакрытый спринт или релиз и как следствие просроченые сроки.

> Учимся работать по конкретно поставленным задачам :grey_exclamation:

**Comment by wilensky** [comment]
@derganyj, [`markdown`][md]

[md]:https://github.com/wilensky/ba-od-idp/wiki/AM:-Markdown-syntax

**Comment by ksahipuk** [comment]
@wilensky любителям повыпендриваться нужно убирать все лишнее из кода?

**Comment by wilensky** [comment]
@ksahipuk, на этот раз всё оставляем как есть.

**Comment by derganyj** [comment]
@wilensky Ok, so no images(
9202b205b091ffd44bfa19f68cd6cecfb621baf1

**Comment by wilensky** [comment]
@derganyj, коммит 9202b20 ведёт на коммит с файлом `.gitkeep` + на ветке кроме этого файла ничего нет. Также стоит проверить `username` и `email` с которыми делается коммит, т.к. что-то из этого не верно. Скорей всего `username`.

**Comment by gorbanev92** [comment]
b9c10ce

**Comment by gorbanev92** [comment]
чисто по заданию.

**Comment by derganyj** [comment]
@wilensky pardon)
I've already corrected the mistake.

**Comment by AndrewBor1** [comment]
Готово!
d994e27

**Comment by wilensky** [comment]
@derganyj, check :exclamation:
```bash
$ git config user.name # Should be your github username
$ git config user.email # Should be your guthub user email
```

**Comment by AndrewBor1** [comment]
Что значит "No newline at end of file" в конце кода html  если просмотреть его через хеш коммита?

**Comment by wilensky** [comment]
@AndrewBor1, Значит, что файл не заканчивается _переводом строки_. Это в основном трогает компиляторы или препроцессоры. То есть и для тех и других критично наличие новой строки в конце каждого файла, а т.к. git используется не только такими как мы, а и другими товарищами, то git на это обращает внимание. В нашем случае наличие пустой строки в конце файла **не критично**. Я стараюсь всегда их убирать и до сегодня проблем не испытываю.

- [No newline at end of file][q1]
- [Why should text files end with a newline?][q2]

[q1]:http://stackoverflow.com/questions/5813311/no-newline-at-end-of-file
[q2]:http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by AndrewBor1** [comment]
@wilensky, спасибо!

**Comment by JulySi35** [comment]
548a7a3

**Comment by tanguera** [comment]
после выполнения 
$ git push origin HEAD
выдалось
Everything up-to-date
что значит?

**Comment by AndrewVoronin** [comment]
@tanguera а вы перед этим делали:
$ git add ******** ?

**Comment by tanguera** [comment]
@AndrewVoronin конечно

**Comment by derganyj** [comment]
@tanguera после git add *  делаете комит командой git commit -m "your massage!", а после этого пуш.

**Comment by AndrewVoronin** [comment]
@tanguera Вы где-то что-то пропустили:
Запускаете GitHub из нужной папки?
Командой сd перемещаетель в свою локальную папку (предположительно: .../www/ba-od-idp/tanguera)?
Вы в ней создали ваш файл?
Вы из нее добавили командой ad?
Дальше "коммитите" и "пушите".

**Comment by tanguera** [comment]
да мальчики, и add, и commit, и push делала в такой последовательности
результат commit'а забыла написать
$ git commit -m "Add first html-file Hello world"
fatal: Unable to create 'D:/www/ba-od-idp/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

**Comment by AndrewVoronin** [comment]
@derganyj У меня в команде $ git add * - "*"(звездочка) - не работает, приходиться указывать принудительно имя файла

**Comment by AndrewVoronin** [comment]
@tanguera А что показывают git status  и  git log?

**Comment by tanguera** [comment]
log послений мой коммит Finally
а status все так же, как и выше писала 
On branch feature/hello-world_tanguera
Changes to be committed:
(use "git reset HEAD ..." to unstage)

    new file:   hello_world.html

**Comment by AndrewVoronin** [comment]
@tanguera reset - не надо, повторите шаги без reset

**Comment by tanguera** [comment]
надо потому как выполнить повторно не получается, какой-то процесс идет 
$ git add hello_world.html
fatal: Unable to create 'D:/www/ba-od-idp/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

последняя строчка диктует, что надо remove

**Comment by AndrewBor1** [comment]
git reset Head по идее уберет файл из index. Надо будет снова делать git add *. Не выполняется команда git commit, т.к. уже существует файл index.lock. Предлагаю его удалить, т.к. подсказывает программа. Для этого:
git cd .git
del index.lock

**Comment by AndrewBor1** [comment]
после попробовать коммитить

**Comment by AndrewBor1** [comment]
точнее так:
cd .git
del index.lock

**Comment by AndrewVoronin** [comment]
@tanguera Я вижу у вас не правильный путь к локальной папке - у вас: D:/www/ba-od-idp/.git/index.lock, а длжно быть D:/www/ba-od-idp/tanguera/hello_world.html

**Comment by tanguera** [comment]
я выше писала результат гит статус 
 $ git status
On branch feature/hello-world_tanguera
Changes to be committed:
(use "git reset HEAD ..." to unstage)

    new file:   hello_world.html
я нахожусь в папке там, где файл хтмл
так как оттудава запустила гит баш хиа

**Comment by tanguera** [comment]
напомните, кто лучше запоминает материал, если мы адд сделали, но передумали коммитить, какая команда нужна?

**Comment by derganyj** [comment]
@tanguera git reset
а вообще, попробуй быстренько просто всё с начала сделать (с самого первого урока) - тебе так легче будет, быстрее и мороки меньше.

**Comment by tanguera** [comment]
)) это в первую очередь сделала

**Comment by tanguera** [comment]
начала эксперименты: @AndrewBor1 ваше предложение $ git cd .git
результат git: 'cd' is not a git command. See 'git --help'.

Did you mean this?
        add

**Comment by AndrewBor1** [comment]
Нет. Сейчас я у себя проверю и отпишу

**Comment by tanguera** [comment]
я догадываюсь, что мне надо остановить/очистить процесс или удалить добавленное в индекс без коммита - но как?

**Comment by AndrewBor1** [comment]
Судя по результатам git status ваш файл добавлен в index успешно. Но после он не коммитится командой commit -m из-за того что уже существует файл index.lock. Попробуй скопировать этот файл вручную из папки .git в любое другое место, а в папке .git его удали и после этого снова сделай commit -m.

**Comment by tanguera** [comment]
пардоньте, я не хочу вручную что-то удалять, а вот командами что-нить удалила бы

**Comment by AndrewBor1** [comment]
что сейчас выдает команда git status?

**Comment by tanguera** [comment]
тоже самое Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git status
On branch feature/hello-world_tanguera
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   hello_world.html

**Comment by AndrewBor1** [comment]
А если сделать git commit -m?

**Comment by tanguera** [comment]
выше писала, ничего не изменилось
Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$  git commit -m "Add first html-file Hello world"
fatal: Unable to create 'D:/www/ba-od-idp/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

**Comment by AndrewBor1** [comment]
Судя из того что выдается я бы удалил index.lock из папки .git предварительно его скопировав в другое место и коммитил снова.

**Comment by tanguera** [comment]
спасибо @AndrewBor1 , я надеюсь найти решение через команды

**Comment by AndrewVoronin** [comment]
@AndrewBor1 для системы должно быть не важно что происходит с другими файлами, она ведь не с ним работает...
Может перегрузить комп и запустить ГитБаш из заново из нужной папки?

**Comment by tanguera** [comment]
)) нее я хочу разобраться командно

**Comment by AndrewBor1** [comment]
Можно попробовать еще git reset HEAD. Эта команда очистит индекс.

**Comment by tanguera** [comment]
пробовала 
результат:
Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git reset HEAD
fatal: Unable to create 'D:/www/ba-od-idp/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

**Comment by wilensky** [comment]
@tanguera, пробуем погуглить и [первый результат в выдаче][so_q]. Ссылка ведёт на правильный ответ, поэтому прочтите внимательно.

> И да, @AndrewBor1 [здесь][comm] посоветовал правильно за что и получает нашивку
> ![Conquest ribbon](http://oyster.ignimgs.com/mediawiki/apis.ign.com/battlefield-3/b/b7/Conquest_rib.png "Conquest ribbon")

---

Проблема в том, что предыдущий процесс создал `.lock` файл для того чтобы предотвратить concurrent operation, но по какой-то причине покрошился и файл не смог быть удалён тем процессом т.к. он завершился внезапно для себя, такое бывает. Поэтому его нужно удалить руками иначе остальные рабочие процессы будут думать, что они лезут вторыми в очереди на коммит и будут срыгивать.

[so_q]:http://stackoverflow.com/a/7860765/1548719
[comm]:https://github.com/wilensky/ba-od-idp/issues/4#issuecomment-161416946

**Comment by tanguera** [comment]
@wilensky эти команды git reset Head, git cd .git, del index.lock не работают, выдает одну ошибку 
fatal: Unable to create 'D:/www/ba-od-idp/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

это значит, что только ручками удалять?

**Comment by wilensky** [comment]
@tanguera, а вас не смущает, что комманды `del` в Git bash не существует?
Это комманда коммандной строки Windows.

Прочитайте еще раз внимательно ответ на SO!

**Comment by tanguera** [comment]
@wilensky  
Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ RM -f /d:/www/ba-od-idp/.git/index.lock

Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git status
On branch feature/hello-world_tanguera
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   hello_world.html

**Comment by sergeyshpota** [comment]
817f5fc

**Comment by AndrewBor1** [comment]
с del это я насоветовал. Сорри)

**Comment by tanguera** [comment]
с той мертвой точки к другой
Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git add hello_world.html

Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git status
On branch feature/hello-world_tanguera

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   hello_world.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitkeep


Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git commit -m "Add first html-file"
[feature/hello-world_tanguera (root-commit) b1b9ebb] Add first html-file
 1 file changed, 33 insertions(+)
 create mode 100644 hello_world.html

Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git push origin HEAD
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by AndrewBor1** [comment]
а что выдает git remote и git remote -v?

**Comment by tanguera** [comment]
Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git remote

Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git remote -v

Nataly@tanguero MINGW64 /d/www/ba-od-idp/tanguera (feature/hello-world_tanguera)
$ git status
On branch feature/hello-world_tanguera
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitkeep

nothing added to commit but untracked files present (use "git add" to track)

**Comment by JulySi35** [comment]
0e479d0 
фух ))

**Comment by tanguera** [comment]
c220bcf УРА

**Comment by wilensky** [comment]
Done!
