### ISSUE TITLE
HW: Lists

### ISSUE THREAD

**Issue by wilensky** [wilensky/ba-od-idp#5]
Yet another homework. We will try to create partial tracklist of _ABGT 159_ from _26.11.2015_.

# &forall; Requirements

* Filename: **`tracklist.html`**
* Additional info about track between `[` and `]` should be _italic_
* Artist name should be **bold**
* Working as usual: <kbd>create</kbd> > <kbd>commit</kbd> > <kbd>push</kbd> > <kbd>comment</kbd>

> :exclamation: Remeber that you have your own **branch** and **directory**

# &there4; How it should look like

#### Tracklist

1. **Andrew Bayer** - Memories
1. **Moonlight Tunes feat. 3PM** - Feeling Alive [_Aleksey Sladkov Dub Mix_]
1. **Johan Vilborg** - Pieces
1. ~~**Enigma** - Sadeness~~
1. **Yotto** - Personal Space
1. **Shadow Child & Ben Pearce** - Nothing Ever Hurts [_Ashworth Remix_]
1. **Matt Fax** - Mirth
1. **Andrea Bertolini** - Peaceful
1. **Spencer Brown** - Lockout
1. **Armin van Buuren feat. Rock Mafia** - Hands To Heaven [_Club Mix_]

## &permil; Progress
- [x] @gorbanev92 
- [x] @ksahipuk 
- [x] @tanguera 
- [x] @derganyj 
- [x] @AndrewVoronin
- [x] @sergeyshpota
- [x] @JulySi35
- [x] @Koval2907
- [x] @AndrewBor1 
- [x] @VityaBeetroot

[abgt159]:http://www.aboveandbeyond.nu/radio/abgt159

**Comment by wilensky** [comment]
@gorbanev92, @ksahipuk, @tanguera, @derganyj, @AndrewVoronin, @sergeyshpota, @JulySi35, @Koval2907, @AndrewBor1, @VityaBeetroot

[![Чотко!](http://s00.yaplakal.com/pics/pics_original/2/9/3/5183392.jpg "Внатуре класс")][video]

[video]:https://youtu.be/o7uDERvtqhc

**Comment by JulySi35** [comment]
Привет. Паш, надо просто этот список написать на HTML?

**Comment by wilensky** [comment]
@JulySi35, всё что под словами **How it should look like** должно быть на странице. А именно:

![](https://cloud.githubusercontent.com/assets/8455569/11588484/ba6d8574-9a89-11e5-8fd5-4566ad4a3861.png)

Со всеми указанными **Requirements**. Поэтому это уже не "просто написать", а выполнить согласно issue #5.

**Comment by ksahipuk** [comment]
done c405e84bdbfd83f8191ee61a6d2c8c8128cee7a6

**Comment by gorbanev92** [comment]
e871b49 =)

**Comment by JulySi35** [comment]
a4c362e

**Comment by JulySi35** [comment]
У меня вопрос: зачем кодировать амперсант, если он и так ставится ?

**Comment by gorbanev92** [comment]
честно, я не проверил и подумал что его в браузере просто так не отобразит, это же спец знак!?

**Comment by gorbanev92** [comment]
правда, можно не кодировать, я проверил и исправил)

**Comment by JulySi35** [comment]
Если открыть свой коммит в github, то знак амперсанта красным подсвечивает, наверное ругается программа на него )))

**Comment by derganyj** [comment]
dca7daab5e1ccc7baecf8a4da8c281f647f5ecdf

**Comment by wilensky** [comment]
@JulySi35, если вспомнить прошлую лекцию, то мы говорили об управляющих последовательностях. Так вот, вспомним формат:
```html
&____;
```
С чего начинается ~~родина~~ управляющая последовательность? Со знака **`&`**.
Так вот `&` может означать начало управляющей последовательности когда её нет, а это может привести к немотивированным поступкам и несанкционированным действиям со стороны браузера. Поэтому, правилом "хорошего тона" является отображение амперсанда с помощью упр. посл.

Поэтому @gorbanev92, рекомендую исправить обратно, а всем остальным помнить об этом (_и в дальнейшем обращать на это внимание_) дабы соответствовать уровню ниньдзи (_если такое желание имеется_).

**Comment by wilensky** [comment]
Братушки, вот вам [маленькая Wiki][lesson_wiki] по прошлому занятию. 

> @gorbanev92, @ksahipuk, @tanguera, @derganyj, @AndrewVoronin, @sergeyshpota, @JulySi35, @Koval2907, @AndrewBor1, @VityaBeetroot

[lesson_wiki]:https://github.com/wilensky/ba-od-idp/wiki/L3:-HTML-basics

**Comment by sergeyshpota** [comment]
53bb6fd

**Comment by AndrewVoronin** [comment]
e17cf09

**Comment by AndrewBor1** [comment]
4c2647d

**Comment by tanguera** [comment]
7aa0b1ab9ae50a3588295cff06805530b0d006ca

**Comment by Koval2907** [comment]
7767d5e

**Comment by VityaBeetroot** [comment]
f78f397

**Comment by VityaBeetroot** [comment]
8937c5b

**Comment by VityaBeetroot** [comment]
dc9eeb7

**Comment by VityaBeetroot** [comment]
dc9eeb7

**Comment by VityaBeetroot** [comment]
dc9eeb7

**Comment by wilensky** [comment]
All done!
