### ISSUE TITLE
HW: Tables

### ISSUE THREAD

**Issue by wilensky** [wilensky/ba-od-idp#6]
Using tracklist from #5 create following table.

# &forall; Requirements

- Filename: **`album_art.html`**
- Use `<table>`s for this task + `<img/>` for sure
- Album art [image link][album_art_image]
- You can omit **`bold`** and _`italic`_ styles for track titles (_we will do it later_)
- Use full tracklist
- Icons? No .. you don't need.

# &there4; How it should look like

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>:musical_score: Author</th>
      <th>:musical_note: Title</th>
      <th>:hourglass: Duration</th>
      <th> :camera: Album art</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Andrew Bayer</td>
      <td>Memories</td>
      <td>1:35</td>
      <td rowspan="3"><img src="http://ecx.images-amazon.com/images/I/51UxkSsMv-L.jpg" title="ABGT album art" /></td>
    </tr>
    <tr>
      <td>2</td>
      <td>Moonlight Tunes feat. 3PM</td>
      <td>Feeling Alive <br/> [Aleksey Sladkov Dub Mix]</td>
      <td>1:25</td>
    </tr>
    <tr>
      <td colspan="4" align="center"><i>... continue tracklist further ...</i></td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">Total duration:</td>
      <td>3:00</td>
      <td align="center">
        <a href="#">:link: Album download link</a>
      </td>
    </tr>
  </tfoot>
</table>

## &permil; Progress
- [x] @gorbanev92 
- [x] @ksahipuk 
- [x] @tanguera 
- [x] @derganyj 
- [x] @AndrewVoronin
- [x] @sergeyshpota
- [x] @JulySi35
- [x] @Koval2907
- [x] @AndrewBor1 
- [x] @VityaBeetroot

[album_art_image]:http://ecx.images-amazon.com/images/I/51UxkSsMv-L.jpg

**Comment by wilensky** [comment]
И, да - [Wiki][wiki].

>  @gorbanev92, @ksahipuk, @tanguera, @derganyj, @AndrewVoronin, @sergeyshpota, @JulySi35, @Koval2907, @AndrewBor1, @VityaBeetroot

[wiki]:https://github.com/wilensky/ba-od-idp/wiki/L4:-Tables

**Comment by ksahipuk** [comment]
Треклист из предыдущего задания брать или оригинальный?

**Comment by derganyj** [comment]
@wilensky I have only one question, how to discover tracks durations?

**Comment by derganyj** [comment]
4f479fd6b39d59576ccc0bcaaa7f525c75b85694

**Comment by ksahipuk** [comment]
12a7fd06e654d76de4b646f69c0e27abe3e243dd

**Comment by AndrewBor1** [comment]
fded33a

**Comment by wilensky** [comment]
@derganyj, track duration = random.

**Comment by sergeyshpota** [comment]
525a6f7

**Comment by AndrewVoronin** [comment]
95a6002

**Comment by VityaBeetroot** [comment]
5ec670f

**Comment by VityaBeetroot** [comment]
5ec670f

**Comment by gorbanev92** [comment]
c3b3cf2

**Comment by gorbanev92** [comment]
c3b3cf2

**Comment by gorbanev92** [comment]
по ошибке закрыл)

**Comment by wilensky** [comment]
:exclamation: Будьте внимательны и обращайте внимание на то **куда и какие кнопки вы нажимаете**, т.к. в реальной жизни это может стригеррить ряд операций которые вы совсем нехотите породить. За что в принципе можно отхватить.

**Comment by JulySi35** [comment]
0ef20bc

**Comment by AndrewVoronin** [comment]
4655202

**Comment by gorbanev92** [comment]
0de9343

**Comment by gorbanev92** [comment]
блин, сори) у меня сегодня дружбы нет с мышкой, мимо жму)

**Comment by wilensky** [comment]
@gorbanev92, ты просто наверное не знаешь чем может быть черевато закрытие ветки в более не менее реальных условиях, а так норм.

**Comment by Koval2907** [comment]
a6d9a61

**Comment by JulySi35** [comment]
cc4e4dd

**Comment by VityaBeetroot** [comment]
a22bdae

**Comment by AndrewBor1** [comment]
html файл с занятия: http://www.ex.ua/745000118346

**Comment by wilensky** [comment]
@AndrewBor1, дуже дякую.

**Comment by tanguera** [comment]
на счет всплывающего текста над текстом Album download link и иконками - нужны?

**Comment by tanguera** [comment]
a8a90abb55f3ec0632b66b50e400d1ec2a543b18
готово

**Comment by VityaBeetroot** [comment]
repetition a22bdae

**Comment by wilensky** [comment]
@VityaBeetroot, сорри, прогнал. Проверил, но не отметил.

**Comment by wilensky** [comment]
10/10. Done.

**Comment by wilensky** [comment]
@tanguera и всем остальным, замечания по поводу неточностей или неверного кода у нас неуместны т.к.:

1. Сейчас делать их могу только я
1. Комментировать под чужими коммитами не имея к ним накого отношения снова могу только я
1. Мы работаем каждый над своей веткой и _code review_ у нас не принят
1. Проводить публичный _code review_ без согласования или явных на то причин - не принято
1. Я проверяю каждый коммит и делаю необходимые замечания
1. Надеюсь зрозумiло ...
1. Следите за своими ветками

> Явная на то причина: QA пропустил явный бок в production. _У нас нет ни QA ни production'а._
