### ISSUE TITLE
HW: Forms

### ISSUE THREAD

**Issue by wilensky** [wilensky/ba-od-idp#7]
# &forall; Requirements
- Look attentively at given form and these requirements.
- Countries list:
 - DE
 - UA
 - ES
- Each control element should have appropriate name (_including `<form>`_).
- Use `<label>` tag with `for` attribute for each applicable control.
- Reset button should reset the whole form. Yes it is possible using HTML only.
- Form should be sent using `POST` on URL `#`.

# &there4; How it should look like

![Contact form][cform]

## &permil; Progress
- [x] @gorbanev92 
- [x] @ksahipuk 
- [x] @tanguera 
- [x] @derganyj 
- [x] @AndrewVoronin
- [x] @sergeyshpota
- [ ] @JulySi35
- [ ] @Koval2907
- [x] @AndrewBor1 
- [x] @VityaBeetroot

[cform]:https://cloud.githubusercontent.com/assets/8455569/11684041/888647b6-9e77-11e5-8435-8a40acd25433.png

**Comment by wilensky** [comment]
[Wiki][wiki]

>  @gorbanev92, @ksahipuk, @tanguera, @derganyj, @AndrewVoronin, @sergeyshpota, @JulySi35, @Koval2907, @AndrewBor1, @VityaBeetroot

[wiki]:https://github.com/wilensky/ba-od-idp/wiki/L5:-Forms

**Comment by ksahipuk** [comment]
святые джигурдинки...

**Comment by ksahipuk** [comment]
db094078362ef29a16d92c6e88b71051089abe4c

![it's done!](http://marccortez.com/wp-content/uploads/2013/12/grumpy-reindeer-269x300.jpg)

**Comment by wilensky** [comment]
Еще раз напоминаю:

- Не знак табуляции, а **4 пробела**.
- Делать дополнительный отступ элементам находящимся на одном уровне - не нужно.
- Если присмотреть внимательней, то форма организована **с помощью таблицы**.
- Мы также должны иметь возможность клацнуть не только на кружочек/квадратик, но и на соответствующую цифру/надпись и получить тот же результат, что и клацнув на сам _checkbox_ или _radio_.

>  @gorbanev92, @ksahipuk, @tanguera, @derganyj, @AndrewVoronin, @sergeyshpota, @JulySi35, @Koval2907, @AndrewBor1, @VityaBeetroot

**Comment by derganyj** [comment]
18157f502c134ae753b9a2655855802dc057d4b7

**Comment by AndrewBor1** [comment]
9fae2ae

**Comment by Koval2907** [comment]
82792cf

**Comment by gorbanev92** [comment]
9e6ab5a

**Comment by AndrewVoronin** [comment]
0ef3f56

**Comment by sergeyshpota** [comment]
db1f7f1

**Comment by tanguera** [comment]
сбросить форму - это сбросить до состояния https://cloud.githubusercontent.com/assets/8455569/11684041/888647b6-9e77-11e5-8435-8a40acd25433.png
или совсем-совсем?

**Comment by tanguera** [comment]
5525f60da80f4f62a9512046b3627a75c25638c1

**Comment by AndrewVoronin** [comment]
UPD: 9696444

**Comment by AndrewVoronin** [comment]
UPD 2: 80d958f

**Comment by tanguera** [comment]
5f179e1e00d35b7d5c830217c2054bb86c130001
изменила CamelCase и label

**Comment by gorbanev92** [comment]
b3837d1 в прошлой версии не закрывал тег <tr> в этой для красоты кода решил всё таки его закрыть везде. и айдишники по CamelCase прописал.

**Comment by JulySi35** [comment]
c6ae582

**Comment by sergeyshpota** [comment]
7752d3c добавил lables

**Comment by VityaBeetroot** [comment]
86e2407

**Comment by VityaBeetroot** [comment]
b589f59 modified

**Comment by tanguera** [comment]
e66e75b3b68e59718b3631510f477ee5ec26c1af перенесла label

**Comment by tanguera** [comment]
2505a435f012be1505e05fd966adbf8072ec78f1 перенесла все label )

**Comment by JulySi35** [comment]
caf4539

**Comment by JulySi35** [comment]
f3b61e3

**Comment by wilensky** [comment]
Done.

**Comment by Koval2907** [comment]
b9e18fa
